# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26f54a00fe3b837c4624470752e007eba2e72461fa7bd28bff30a90950a8a9de6f2fa34d63985ccd91d5e4356714a520b1933a33cea7e867b295c58e1c7b4abc

test:
  secret_key_base: 2b58ff31c50cbb94722760d20c1789a931fd9d5f1ca5a3d9806b95b2609337923829d9e0d4a2cb872289d630e86dabb2aeecbb28dc6b179a36a116f0880da2bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
