# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bbee011cf70f3067857dc204b50e61c0c5af66e00b35182b0710c6e3004f1bb4ddfff6dc9f3b351ebb8f4f50d296ac9d351f5b1be2f6f8dc17c894ee16c0c44

test:
  secret_key_base: a3cf049116cd339d7753cee4d5f0274074b53863507e9f10e1979178114d4d1103c5567b60563615e1f8db4d277c56e9ea86a0b80f17f4d2467e5026ba9d97b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
